## Tensores en PyTorch

In [ ]:
import torch
vector = [1, 2, 3, 4, 5]
vT = torch.tensor(vector)
print(vT)

tensor([1, 2, 3, 4, 5])


In [ ]:
type(vT)

torch.Tensor

In [ ]:
vT.shape

torch.Size([5])

In [ ]:
import torch
  
x = torch.randn((3, 4, 5))
print(x)

tensor([[[ 0.9684, -0.2139, -0.4920,  0.6514,  0.2877],
         [ 0.1304, -0.4579, -1.0138, -1.1040,  0.0424],
         [ 1.0343,  0.3267, -0.3842,  0.6621, -0.5814],
         [-0.1205,  0.8856,  0.9755,  0.1032,  0.7239]],

        [[ 0.2731,  0.9171, -0.1134, -0.5830,  0.6250],
         [ 0.7236,  1.0390,  0.9530,  1.3120, -1.1748],
         [-1.7936, -1.9089, -0.8525,  1.9468, -0.2974],
         [ 0.9734, -0.0411,  1.5648,  1.0405, -0.9282]],

        [[-0.8225, -1.1806, -0.4615,  0.2561,  1.9205],
         [ 0.0873, -0.7382,  0.2289, -0.6730,  0.6466],
         [ 1.0109, -1.8077,  1.3578, -1.0219, -0.8209],
         [-1.6808,  1.0308, -0.1272, -0.0127, -0.9545]]])


In [ ]:
type(x)

torch.Tensor

In [ ]:
x.shape

torch.Size([3, 4, 5])

In [ ]:
z= torch.zeros([3,3], dtype=torch.int32)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [ ]:
z.shape

torch.Size([3, 3])

In [ ]:
newT= torch.full((4, 3), 3.14,dtype= torch.float32)
print(newT)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])


In [ ]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [ ]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x - y
print(z)

tensor([-3., -3., -3.])


In [ ]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x * y
print(z)

tensor([ 4., 10., 18.])


In [ ]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x / y
print(z)

tensor([0.2500, 0.4000, 0.5000])


In [ ]:
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
print(x_1,'\n', y_1)

tensor([[ 1.4096,  0.9150,  0.2178, -0.5789,  0.5906],
        [ 2.4075, -0.2022, -0.6446,  0.0796,  0.0824]]) 
 tensor([[ 0.2131, -0.5414, -0.1088, -0.3068, -0.6573],
        [-0.8448, -2.2483,  0.1308,  0.4612,  0.4343],
        [ 0.7719, -0.5669, -1.5591, -1.0846, -0.5047]])


In [ ]:
z_1 = torch.cat([x_1, y_1])
print(z_1)

tensor([[ 1.2057,  0.1333,  0.9187, -1.6085,  0.8315],
        [ 0.2785,  0.6051,  0.4358,  0.5733, -0.0873],
        [-0.5715, -1.3809, -1.5970,  0.1197, -0.8898],
        [ 1.0206,  0.5372, -1.5092,  0.4153,  0.8895],
        [ 0.9598,  1.8554,  1.0688, -0.5165,  1.1954]])
